onEvent('jei.information', e => {
	//===== astral sorcery =====//
	e.add('astralsorcery:stardust', 'Stardust is obtained from throwing the starmetal ingot on the ground, then left-clicking the ingot item with a starmetal cutting tool.')
	e.add(['astralsorcery:perk_gem_day', 'astralsorcery:perk_gem_night', 'astralsorcery:perk_gem_sky'], 'The dynamism gem is obtained from throwing a illumination powder and a rock crystal into a pool of liquid starlight.')
	e.add('astralsorcery:illumination_wand', 'Combine with any color of dye to change the color of light.')
    e.add('astralsorcery:celestial_crystal', 'Throw a rock crystal and a stardust into a pool of liquid starlight, which should be on a starmetal ore. Focus starlight from a collector crystal onto the starmetal ore and the pool of liquid starlight. Wait a while to obtain the celestial crystal. Note that the crystal properties are independent to the rock crystal.')
	e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:discidia"}}'), ['Sagittarius (Discidia)', 'Return the damage taken from enermies in your next hit.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:armara"}}'), ['Capricornus (Armara)', 'Store up to 3 magical charges per minute. Each charges allow you to neglect one damaging attack.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:vicio"}}'), ['Gemini (Vicio)', 'Grant the effect of elytra but with greater speed and no decay to the mantle.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:aevitas"}}'), ['Virgo (Aevitas)', 'Recovers hunger while walking. Spawn an invisible platform when you are falling.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:evorsio"}}'), ['Aries (Evorsio)', 'Allows you to break planes of blocks at once.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:lucerna"}}'), ['Libra (Lucerna)', 'Reveals entites, spawners and containers in 36 blocks radius.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:mineralis"}}'), ['Taurus (Mineralis)', 'Reveals the blocks you are holding in 20 blocks radius.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:horologium"}}'), ['Scorpius (Horologium)', 'Freeze all hostiles when attacked (exclude fire) for a short peroid of time, with a short time delay.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:octans"}}'), ['Pisces (Octans)', 'Reduce water resistance against moving and mining. Grant you water-breathing effect.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:bootes"}}'), ['Aquarius (Bootes)', 'Spawn 3 flares that attacks your enermies.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:fornax"}}'), ['Leo (Fornax)', 'Fire damage regenerates your health.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"astralsorcery:pelotrio"}}'), ['Cancer (Pelotrio)', 'Manifest starlight into animated tools and weapons during being used, and mimicking the your behavior.'])
    e.add(Item.of('astralsorcery:mantle', '{astralsorcery:{constellationName:"naturesstarlight:naritis"}}'), ['Naritis', 'Equals Skyseeker chesplate. An Aura Cache in your posession will be slowly filled with Aura.'])
    //===== mekanism =====//
	e.add('mekanism:creative_energy_cube',
	['Place two ultimate induction provide on the two sides of the creative energy cube.',
	 'Then place two FULLY CHARGED ultimate energy cube on the opposing two sides of the ultimate induction provide.',
	 'A 5-block straight line should be formed. Charge the creative energy cube with sneak-right clicking with a redstone torch.'])
	//===== coloured items =====//
	let colors = ['white', 'light_gray', 'gray', 'black', 'red', 'orange', 'yellow', 'lime', 'green', 'light_blue', 'cyan', 'blue', 'purple', 'magenta', 'pink', 'brown']
	colors.forEach(color => {
		e.add(`minecraft:${color}_wool`, 'Put any colour of wool together with a dye in crafting table to get specific colour of wool.')
		e.add(`thermal:${color}_rockwool`, 'Put any colour of wool together with a dye in crafting table to get specific colour of wool.')
		e.add(`minecraft:${color}_bed`, 'Craft the bed with any colour of wool to get that specific colour of bed.')
		e.add(`minecraft:${color}_stained_glass`, 'Surround a dye with 8x any types of glass to get the specific colour of stained glass.')
		e.add(`minecraft:${color}_stained_glass_pane`, 'Surround a dye with 8x any types of glass plane to get the specific colour of stained glass plane, or directly craft the glass plane with 6x particular colour of glass.')
		e.add(`minecraft:${color}_concrete_powder`, 'Craft the concrete powder with any colour of dye with 4x sand and 4x gravel to get the colourled concrete powder.')
		e.add(`minecraft:${color}_concrete`, 'Concrete is created by hydrating concrete powder by water, or check JEI for recipes')
		e.add(`minecraft:${color}_carpet`, 'Craft the carpet with any colour of wool to get that specific colour of carpet.')
		e.add(`quark:${color}_quilted_wool`, 'Craft the quilted wool with any colour of wool to get that specific colour of quilted wool.')
        e.add(`quark:${color}_framed_glass`, 'This item can be crafted with any colour.')
        e.add(`quark:${color}_framed_glass_pane`, 'This item can be crafted with any colour.')
        e.add(`connectedglass:borderless_glass_${color}`, 'This item can be crafted with any colour.')
        e.add(`connectedglass:clear_glass_${color}`, 'This item can be crafted with any colour.')
        e.add(`connectedglass:scratched_glass_${color}`, 'This item can be crafted with any colour.')
        e.add(`connectedglass:borderless_glass_${color}_pane`, 'This item can be crafted with any colour.')
        e.add(`connectedglass:clear_glass_${color}_pane`, 'This item can be crafted with any colour.')
        e.add(`connectedglass:scratched_glass_${color}_pane`, 'This item can be crafted with any colour.')
        e.add(`connectedglass:tinted_borderless_glass_${color}`, 'This item can be crafted with any colour.')
        e.add(`absentbydesign:slab_glass_${color}`, 'This item can be crafted with any colour.')
        e.add(`absentbydesign:stairs_glass_${color}`, 'This item can be crafted with any colour.')
        e.add(`absentbydesign:wall_glass_${color}`, 'This item can be crafted with any colour.')
        e.add(`absentbydesign:stairs_wool_${color}`, 'This item can be crafted with any colour.')
        e.add(`absentbydesign:slab_wool_${color}`, 'This item can be crafted with any colour.')
        e.add([
            `botanypotstiers:elite_${color}_botany_pot`,
            `botanypotstiers:ultra_${color}_botany_pot`,
            `botanypotstiers:creative_${color}_botany_pot`,
            `botanypots:${color}_botany_pot`,
            `botanypots:hopper_${color}_botany_pot`,
            `botanypotstiers:elite_hopper_${color}_botany_pot`,
            `botanypotstiers:ultra_hopper_${color}_botany_pot`,
            `botanypotstiers:creative_hopper_${color}_botany_pot`
        ], 'Bontany pots can be crafted with any colour of terracotta!')
    })
	//===== interconversion =====//
	e.add(['minecraft:oak_boat', 'minecraft:chest', 'minecraft:bookshelf', 'minecraft:barrel', 'minecraft:oak_sign', 'minecraft:crafting_table'], 'You can place any wood variation items onto crafting table to get the vanilla version.')
    e.add(['astralsorcery:marble_raw', 'chisel:marble/raw', 'chisel:limestone/raw', 'create:limestone', 'create:weathered_limestone', 'chisel:basalt/raw', 'minecraft:basalt'], 'You can place this to crafting table to get another version.')
	//===== draconic evolution =====//
	e.add('draconicevolution:chaos_shard', 'Obtained by defeating chaos guardian spawning every 20000 blocks in the End dimension.')
	e.add('draconicevolution:creative_capacitor', 'You have to use creative energy source from Draconic Evolution to craft this item.')
    //===== create =====//
    e.add('create:refined_radiance','Throw Chromatic Compound in a Beacon beam, or near light sources')
    e.add('create:shadow_steel','Throw Chromatic Compound into the void, ideally in the End, and it will float back up as Shadow Steel')
    e.add('create:blaze_burner','Use an Empty Blaze Burner on a Blaze')
	//===== blood magic =====//
	e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:5000,key:"bloodmagic:self_sacrifice"}]}}),['Tough Palms','Grants bonus to self sacrifice, up to 150%%',' ','Trained by using the Sacrificial Knife'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:70000,key:"bloodmagic:speed"}]}}),['Quick Feet','Grants bonus to speed, up to 150%%',' ','Trained by sprinting'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:10000,key:"bloodmagic:health"}]}}),['Healthy','Grants additional health, up to 50 half-hearts',' ','Trained by restoring health by natural means, or potions'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:15000,key:"bloodmagic:arrow_protect"}]}}),['Pin Cushion','Grants resistance to arrows',' ','Trained by being shot by arrows'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:15000,key:"bloodmagic:physical_protect"}]}}),['Tough','Grants resistance to melee damage',' ','Trained by being hit by melee damage'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:3800,key:"bloodmagic:sprint_attack"}]}}),['Charging Strike','Grants bonus attack damage while sprinting, up to 50%%',' ','Trained by dealing damage while sprinting'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:14000,key:"bloodmagic:experienced"}]}}),['Experienced','Grants increased XP from killing mobs, up to 150%%',' ','Trained by collecting XP'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:1500,key:"bloodmagic:fall_protect"}]}}),['Soft Fall','Grants reduced fall damage, up to 100%%',' ','Trained by taking fall damage'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:5000,key:"bloodmagic:jump"}]}}),['Strong Legs','Grants increased jump height and reduced fall damage, up to 7.5 blocks high and 83%% damage resist',' ','Trained by jumping'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:30000,key:"bloodmagic:poison_resist"}]}}),['Poison Resistance','Grants immunity to poison, with a cooldown that increases by level',' ','Trained by being poisoned'])
    e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:30000,key:"bloodmagic:fire_resist"}]}}),['Gift of Ignis','Grants fire resistance, higher levels last longer and recharge faster',' ','Trained by taking fire damage'])
    e.add('bloodmagic:quick_draw_anointment',['Lowers the draw time of bows and crossbows by 33%%','Lasts 256 shots'])
    e.add('bloodmagic:quick_draw_anointment_l',['Lowers the draw time of bows and crossbows by 33%%','Lasts 1024 shots'])
    e.add('bloodmagic:quick_draw_anointment_2',['Lowers the draw time of bows and crossbows by 50%%','Lasts 256 shots'])
    e.add('bloodmagic:fortune_anointment',['Increases the yield of certain harvested blocks','Stacks with Fortune','Lasts 256 blocks'])
    e.add('bloodmagic:fortune_anointment_l',['Increases the yield of certain harvested blocks','Stacks with Fortune','Lasts 1024 blocks'])
    e.add('bloodmagic:fortune_anointment_2',['Further increases the yield of certain harvested blocks','Stacks with Fortune','Lasts 256 blocks'])
    e.add('bloodmagic:holy_water_anointment',['Increases the damage dealt to undead mobs by 5','Lasts 256 strikes'])
    e.add('bloodmagic:holy_water_anointment_l',['Increases the damage dealt to undead mobs by 5','Lasts 1024 strikes'])
    e.add('bloodmagic:holy_water_anointment_2',['Increases the damage dealt to undead mobs by 10','Lasts 256 strikes'])
    e.add('bloodmagic:melee_anointment',['Increases damage dealt by 3','Lasts 256 strikes'])
    e.add('bloodmagic:melee_anointment_l',['Increases damage dealt by 3','Lasts 1024 strikes'])
    e.add('bloodmagic:melee_anointment_2',['Increases damage dealt by 6','Lasts 256 strikes'])
    e.add('bloodmagic:bow_power_anointment',['Increases the damage of fired arrows and bolts by 25%%','Stacks with Power','Lasts 256 shots'])
    e.add('bloodmagic:bow_power_anointment_l',['Increases the damage of fired arrows and bolts by 25%%','Stacks with Power','Lasts 1024 shots'])
    e.add('bloodmagic:bow_power_anointment_2',['Increases the damage of fired arrows and bolts by 50%%','Stacks with Power','Lasts 256 shots'])
    e.add('bloodmagic:hidden_knowledge_anointment',['Harvested blocks drop 2 xp','Lasts 256 blocks'])
    e.add('bloodmagic:hidden_knowledge_anointment_l',['Harvested blocks drop 2 xp','Lasts 1024 blocks'])
    e.add('bloodmagic:hidden_knowledge_anointment_2',['Harvested blocks drop more xp','Lasts 256 blocks'])
    e.add('bloodmagic:looting_anointment',['Increases drops from killed mobs','Stacks with Looting','Lasts 256 strikes'])
    e.add('bloodmagic:looting_anointment_l',['Increases drops from killed mobs','Stacks with Looting','Lasts 1024 strikes'])
    e.add('bloodmagic:looting_anointment_2',['Further increases drops from killed mobs','Stacks with Looting','Lasts 256 strikes'])
    e.add('bloodmagic:smelting_anointment',['Smelts harvested blocks','Lasts 256 blocks'])
    e.add('bloodmagic:smelting_anointment_l',['Smelts harvested blocks','Lasts 1024 blocks'])
    e.add('bloodmagic:silk_touch_anointment',['Applies Silk Touch','Lasts 256 blocks'])
    e.add('bloodmagic:silk_touch_anointment_l',['Applies Silk Touch','Lasts 1024 blocks'])
    //===== Botania =====//
    e.add('botania:lens_normal', 'A lens can be dyes with any types of colour, or combines with mana pearl and turns into rainbow lens. Use a slime ball to combine two lenses.')
    e.add('botania:lens_speed', 'Increase speed but lower initial capacity and faster mana loss.')
    e.add('botania:lens_power', 'Double initial capacity, but travel slower and faster mana loss.')
    e.add('botania:lens_time', 'Reduce mana loss, but reduce speed.')
    e.add('botania:lens_efficiency', 'Decrease rate of mana loss, but decrease the time needed to start mana loss')
    e.add('botania:lens_messenger', 'Increase speed and maximum distance, but decrease initial capacity.')
    e.add('botania:lens_bounce', 'Allow mana burst to bounce off walls.')
    e.add('botania:lens_gravity', 'Allow mana burst to be affected by gravity and increase the time needed to start mana loss.')
    e.add('botania:lens_mine', 'Allow mana burst to break blocks.')
    e.add('botania:lens_damage', 'Allow mana burst to damage entities.')
    e.add('botania:lens_phantom', 'Allow mana burst to pass through blocks.')
    e.add('botania:lens_magnet', 'Allow mana burst to magnetize nearby blocks that can reveice mana, but slightly decrease speed of burst')
    e.add('botania:lens_explosive', 'Allow mana burst to explode if in contact with things that cannot receive mana.')
    e.add('botania:lens_influence', 'Allow mana burst to influence nearby dropped items, experience orbs, or falling blocks to move in the same direction with it.')
    e.add('botania:lens_weight', 'Allow mana burst to cause nearby blocks to be affected by gravity.')
    e.add('botania:lens_fire', 'Allow mana burst to ignite blocks, excluding entities.')
    e.add('botania:lens_piston', 'Allow mana burst to push blocks away.')
    e.add('botania:lens_light', 'Allow mana burst to create a flame on block and provide light, which is purely decorative.')
    e.add('botania:lens_paint', 'Allow mana burst to change colour of entities or blocks. Craft with desired colour of wool to decide colour.')
    e.add('botania:lens_warp', 'Prevent mana burst to break force relays or pistons.')
    e.add('botania:lens_redirect', 'Allow mana burst to turn another mana spreader towards the one that fired the burst.')
    e.add('botania:lens_firework', 'Allow mana burst to create firework dyed with colour of burst.')
    e.add('botania:lens_flare', 'Allow mana burst to fire continuously. Decorative purpose.')
    e.add('botania:lens_tripwire', 'Allow mana burst to fire only when it would hit entities')
    e.add('extrabotany:lens_mana', 'Allow mana burst to infuse items, just like a mana pool.')
    e.add('extrabotany:lens_push', 'Allow mana burst to push entity away.')
    e.add('extrabotany:lens_trace', 'Allow mana burst to trace the first detected entities within 3 blocks radius.')
    e.add('extrabotany:lens_smelt', 'Allow mana burst to smelt blocks.')
    e.add('extrabotany:lens_potion', 'Allow mana burst to grant effects. Craft with brew flash to decide effects.')
    e.add('mythicbotany:fimbultyr_tablet', 'This is obtained by defeating Gaia II after drinking "Mead of Kvasir".')
    //===== integrated dynamics =====//
    e.add('integrateddynamics:energy_battery', 'You can combine several battery together to enlarge the storage amount.')
    e.add('integrateddynamics:wrench', 'Automatic systems from Integrated Dynamics is disabled and hidden due to severe lag due to poor optimization of thei mod.')
    //===== Dungeons Mod =====//
    e.add('dungeonsmod:unstable_map', 'Spawn in loot chests in overworld structure "The Sewer" found deep in the beach biome. Open the map in the End dimension helps you find the location of Void Master. Opening the map in overworld will make the map lost.')

})